language: node_js
node_js:
  - "0.12"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - node_modules

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test
